Repository DEFRA/waste-permits, pull requests merged in 2019-12, with the labels that each got.

#785 WE-3141: Climate change task is correctly displayed in tasklist
  src/models/taskList/bespoke.taskList.js
Labels: fix

#787 WE-3273: Check for decimals in director DOB
  src/controllers/directorDateOfBirth.controller.js
  test/routes/directorDateOfBirth.route.test.js
  test/routes/permitHolder/permitHolderNameAndDateOfBirth.route.test.js
Labels: fix

#788 WE-3340: Confirm activities and assessments total cost issue
  src/models/applicationCost.model.js
  test/models/applicationCost.model.test.js
Labels: fix

#791 WE-3141: Climate change risk screening amendments
  src/controllers/climateChangeRiskScreening/permitLength.controller.js
  src/models/climateChangeRiskScreening.model.js
  src/views/climateChangeRiskScreening/permitLength.html
  test/helpers/mocks.js
  test/routes/climateChangeRiskScreening/permitLength.route.test.js
Labels: feature, fix

#792 WE-3296: Update task lists
  src/routes.js
  src/tasks.js
  test/models/taskList/base.taskList.test.js
Labels: feature

#793 WE-3300: Clinical Waste Documents content
  src/routes.js
  src/views/upload/clinicalWasteDocuments/justification.html
  test/routes/clinicalWasteDocuments/justification.route.test.js
  test/routes/clinicalWasteDocuments/storeTreat.route.test.js
Labels: fix

#794 WE-3342: Add text to Confirm activities screen
  src/views/confirmCost.html
Labels: feature

#795 We 3325 fix waste activities task list
  src/controllers/wasteWeight.controller.js
  src/models/wasteWeights.model.js
  test/models/wasteWeights.model.test.js
Labels: fix

#796 WE-3331: Hazardous waste summary content
  src/views/upload/hazardousWaste/hazardousWasteTreatmentSummary.html
Labels: fix

#797 WE-3351: add filter for discount lines and amend test
  src/models/wasteDisposalAndRecoveryCodes.model.js
  test/models/wasteDisposalAndRecoveryCodes.model.test.js
Labels: fix

#799 WE-3345: Waste weights content change
  src/views/wasteWeight.html
Labels: fix

#798 WE-3344: Noise and vibration additional filetypes
  src/constants.js
  src/routes.js
  test/routes/noiseVibrationDocuments.route.test.js
Labels: feature

#800 WE-1761: Re-order Check your answers
  src/models/checkList/checkList.js
  src/models/checkList/technicalStandards.check.js
  src/models/taskList/technicalStandards.task.js
  test/models/checkList/technicalStandards.check.test.js
Labels: fix

#801 WE-3347: Amended noise and vibration emissions upload page content
  src/views/upload/noiseVibrationDocuments/noiseVibrationDocuments.html
Labels: fix

#802 WE-3336: Amend PDF for bespoke applications
  src/services/pdf.js
  test/services/pdf.test.js
Labels: fix

#803 WE-3141: Remove redirection for completed climate change screening
  src/controllers/climateChangeRiskScreening/permitLength.controller.js
  test/routes/climateChangeRiskScreening/permitLength.route.test.js
Labels: fix

#804 WE-3141: Content update
  src/views/upload/climateChangeRiskScreening/climateChangeRiskScreening.html
  test/routes/climateChangeRiskScreening/permitLength.route.test.js
Labels: fix

#805 WE-3354: PDF fails for Waste Bespoke
  src/models/checkList/bespokePermit.check.js
  src/models/checkList/checkList.js
  src/models/taskList/bespoke.taskList.js
  src/services/pdf.js
Labels: fix
